# Generated by Django 3.2 on 2021-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
